### ISSUE TITLE
ID count per server

### ISSUE THREAD

**Issue by PenguinKnight303** [bumblepie/haikubot#41]
It's no fun having to guess at IDs hoping they're from your server.

**Comment by bumblepie** [comment]
I think this would be better served by giving search functionality honestly

**Comment by PenguinKnight303** [comment]
I kinda like being able to roll through some at random though. Maybe pair search with a random haiku function.

**Comment by bumblepie** [comment]
yep, fetching a random haiku from the server is definitely a valid use case, so I think having a command for that would be nice.

**Comment by PenguinKnight303** [comment]
Search + Random would mean you rarely need by ID so yeah fair enough. Maybe ID should be random rather than sequential in that case?

**Comment by bumblepie** [comment]
I'm gonna close this issue and open two new issues for search and random commands respectively since they provide the expected behaviour

**Comment by bumblepie** [comment]
Opened #48 and #47
